# spring.application.name=ms-rutaexpress-catalog

# spring.datasource.url=jdbc:h2:mem:catalogdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=update

# #consolaweb
# spring.h2.console.enabled=true 
# server.port=8083

spring.application.name=ms-rutaexpress-catalog
server.port=8083

spring.datasource.url=${DB_URL:jdbc:h2:mem:catalogdb}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true